
MAZE_WIDTH = 21            # number of columns
MAZE_HEIGHT = MAZE_WIDTH    # number of rows

DEBUG_MODE = False
MARK_TRAIL = True

MAX_STRAIT_LINE = max(2, int(MAZE_WIDTH/5))
MIN_ROWS_TO_SPLIT_POLYGON = 3
MAX_POLYGON_PERCENTAGE_AREA = 1 #0.25

LINE_SIZE = 20
NO_TRAIL_LINE_COLOR = 'black'
LEFT_TRAIL_LINE_COLOR = 'red'
RIGHT_TRAIL_LINE_COLOR = 'blue'
BOTH_SIDES_TRAIL_LINE_COLOR = 'black'
SHOW_CELL_COLOR = 'green'

X_00 = Y_00 = LINE_SIZE


