
MAZE_WIDTH = 30             # number of columns
MAZE_HEIGHT = MAZE_WIDTH    # number of rows

DEBUG_MODE = False
MARK_TRAIL = True

DIVIDERS_RESOLUTION = 2
MAX_STRAIT_LINE = 6
MAX_ADD_TO_PART_SIZE = 2

LINE_SIZE = 20
NO_TRAIL_LINE_COLOR = 'black'
LEFT_TRAIL_LINE_COLOR = 'red'
RIGHT_TRAIL_LINE_COLOR = 'blue'
BOTH_SIDES_TRAIL_LINE_COLOR = 'yellow'

X_00 = Y_00 = LINE_SIZE

